file1 = open('test_data.txt')
file2 = open('test_data.txt')
file3 = open('test_data.txt')
file4 = open('test_data.txt')
file6 = open('test_data.txt')
file5 = open('test_data.txt', 'r+')

print(file1)
print('-'*100)
print(file1.read())
print('-'*100)
print('tell - ', file2.tell())
print(file2.read(10))
print('tell - ', file2.tell())
file2.seek(6)
print('tell - ', file2.tell())
print('-'*100)
print(file2.read(10))
print('tell - ', file2.tell())
print('-'*100)
print(file3.readline())
print('-'*100)
print(file3.readline())
print('-'*100)
print(file3.readline())
print('-'*100)
print(file4.readlines())
print('-'*100)
print('-'*100)
print(file5.read(3))
print('tell - ', file5.tell())
file5.seek(4)
print('tell - ', file5.tell())
print(file5.write('TEST'))
file5.flush()
print(file6.read())
print('-'*100)
file5.close()
print('-'*100)
print('-'*100)
with open('test_data.txt', 'w') as file8:
    file8.writelines(['START\n', '1, 2, 3\n', 'END'])
print(open('test_data.txt').read())



